### PR TITLE
feat(logging): Add logging react-query

### PR DESCRIPTION
**Pull request by martwozniak**

### CODE REVIEW

**Review by grski — CHANGES_REQUESTED** [review]
hm, i'll later prepare alternative solution

**Comment by grski** [comment]
```
#logs.ts

import {LOG_INCOMING_MESSAGES, LOG_TRIM_MESSAGES} from "@/utils/app/const";
import {ChatBody} from "@/types/chat";

function logOpenAIRequest(body: ChatBody, user: string | null | undefined) {
    if (LOG_INCOMING_MESSAGES) {
      let chatBody = body as ChatBody;
      if (LOG_TRIM_MESSAGES) {
        chatBody.messages = chatBody.messages.slice(-1);
      }
      const logMessage = {
          data: chatBody,
          user: user,
      }
      console.log(JSON.stringify(logMessage));
    }
}

export { logOpenAIRequest }
```

**Comment by martwozniak** [comment]
Currently without this function:
` logOpenAIRequest(body, token?.email);`
because this branch doesnt contain next-auth so I cannot use user data (`token?.email`).

**Review by grski — APPROVED** [review]
better

**Pull request merged**
